############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
name = "Elements"
url = "/elements"
weight = 4

# [[main]]
# weight = 3
# name = "Topics"

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Topics"
# name = "Linux"
# url = "/Linux"

# [[main]]
# parent = "Topics"
# name = "C++"
# url = "/C++"

# [[main]]
# parent = "Topics"
# name = "Docker"
# url = "/Docker"

# [[main]]
# parent = "Topics"
# name = "iOS & Swift"
# url = "/iOS_Swift"

# [[main]]
# parent = "Topics"
# name = "Python"
# url = "/Python"

# footer menu
[[footer]]
name = "Categories"
url = "/categories"
weight = 1

[[footer]]
name = "Tags"
url = "/tags"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
